export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  CREDENTIALS = 'CREDENTIALS',

  // HTTP Status Codes
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
}
