name: API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: 'test'
      PORT: 3001
      DATABASE_URL: 'postgres://user:password@localhost:5432/bd?schema=public'
      FRONTEND_URL: 'http://localhost:5173'
      JWT_SECRET: 'sua_chave'
      GOOGLE_CLIENT_ID: '123'
      GOOGLE_CLIENT_SECRET: '123'
      GOOGLE_CALLBACK_URL: 'http://localhost:3001/auth/google/callback'
      PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Cache Prisma binaries
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/prisma
          node_modules/.prisma
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-prisma-

    - name: Delete script prepare
      run: npm pkg delete scripts.prepare

    - name: Install dependencies
      run: npm ci

    - name: Run Linting
      run: npm run ci:lint

    - name: Run Typechecking
      run: npm run typecheck